---

- hosts: all

  tasks:

    - name: install neovim
      ansible.builtin.pip:
        name: neovim
        state: latest
      become: yes

    - name: create dir for old neovim config
      ansible.builtin.file:
        force: yes
        dest: ~/.config/nvim_old
        state: directory

    - name: link config files
      ansible.builtin.file:
        force: yes
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
        mode: 0755
      loop:
        - { src: '{{ curdir }}/config/.zshrc', dest: ~/.zshrc }
        - { src: '{{ curdir }}/config/.bashrc', dest: ~/.bashrc }
        - { src: '{{ curdir }}/config/nvim_old/init.vim', dest: ~/.config/nvim/init.vim }
        - { src: '{{ curdir }}/config/nvim_old/coc-settings.json', dest: ~/.config/nvim/coc-settings.json }

        - get_url:
                force: yes
                dest: ~/.local/share/nvim/site/autoload/plug.vim
                url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"

        # TODO Добавить билд flameshot (для скриншотов), найти аудио-плеер (возможно консольный)
        # TODO Добавить устрановку шрифта JetBrainsMono (nerd font):
        # /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/install_manual.sh)"
        # TODO Добавить устрановку libinput-gestures из aur
          # tags:
          #       - all
