---

- hosts: all

  tasks:

        - file:
                dest: ~/.config/nvim
                state: directory

        - file:
                src: "{{ curdir }}/config/nvim/init.vim"
                dest: ~/.config/nvim/init.vim
                state: link

        - pip: name=neovim state=latest
          become: yes
        
        - file: path=~/.local/share/nvim/site/autoload state=directory recurse=Yes
          with_items:
                  - autoload

        - get_url:
                force: yes
                dest: ~/.local/share/nvim/site/autoload/plug.vim
                url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"


        - pacman:
                name: "{{ item }}"
                state: latest
          ignore_errors: true
          become: true
          with_items:
                - the_silver_searcher
                - zsh
                - fzf
          tags:
                - all
                - arch
